using System.Reflection;
using System.Text;
using UnityPackageScanner.Core.Analysis;
using UnityPackageScanner.Rules;

// Instantiate all rules via reflection and generate docs/rules.md.
// Run: dotnet run --project tools/RulesDocGenerator

var outputPath = args.Length > 0
    ? args[0]
    : Path.Combine(FindRepoRoot(), "docs", "rules.md");

var rules = DiscoverRules();

if (rules.Count == 0)
{
    Console.Error.WriteLine("ERROR: No IDetectionRule implementations found.");
    return 1;
}

var sb = new StringBuilder();
sb.AppendLine("# Detection Rules");
sb.AppendLine();
sb.AppendLine("This file is auto-generated by `tools/RulesDocGenerator`. Do not edit by hand.");
sb.AppendLine($"Generated: {DateTimeOffset.UtcNow:yyyy-MM-dd}");
sb.AppendLine();

var grouped = rules
    .GroupBy(r => r.DefaultSeverity)
    .OrderByDescending(g => g.Key);

foreach (var group in grouped)
{
    sb.AppendLine($"## {group.Key}");
    sb.AppendLine();

    foreach (var rule in group.OrderBy(r => r.RuleId))
    {
        sb.AppendLine($"### {rule.Title} (`{rule.RuleId}`)");
        sb.AppendLine();
        sb.AppendLine($"**Severity:** {rule.DefaultSeverity}");
        sb.AppendLine();
        sb.AppendLine(rule.LongDescription);
        sb.AppendLine();

        if (rule.FalsePositivePatterns.Count > 0)
        {
            sb.AppendLine("**Common false positives:**");
            sb.AppendLine();
            foreach (var fp in rule.FalsePositivePatterns)
                sb.AppendLine($"- {fp}");
            sb.AppendLine();
        }
    }
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Generated {outputPath} ({rules.Count} rules)");
return 0;

static List<IDetectionRule> DiscoverRules()
{
    var rulesAssembly = typeof(InitializeOnLoadRule).Assembly;
    var results = new List<IDetectionRule>();
    var loggerFactory = Microsoft.Extensions.Logging.Abstractions.NullLoggerFactory.Instance;

    foreach (var type in rulesAssembly.GetTypes())
    {
        if (type.IsAbstract || type.IsInterface) continue;
        if (!typeof(IDetectionRule).IsAssignableFrom(type)) continue;

        try
        {
            // Try the single-constructor that takes ILogger<T>
            var ctor = type.GetConstructors().FirstOrDefault();
            if (ctor is null) continue;

            var ps = ctor.GetParameters();
            if (ps.Length == 1 && ps[0].ParameterType.IsGenericType)
            {
                // ILogger<TRule>
                var logger = loggerFactory.CreateLogger(type.FullName ?? type.Name);
                // We need ILogger<T> not ILogger; create via generic method
                var createMethod = typeof(Microsoft.Extensions.Logging.LoggerFactoryExtensions)
                    .GetMethods()
                    .First(m => m.Name == "CreateLogger" && m.IsGenericMethod)
                    .MakeGenericMethod(type);
                var typedLogger = createMethod.Invoke(null, [loggerFactory]);
                var rule = (IDetectionRule)ctor.Invoke([typedLogger]);
                results.Add(rule);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"WARN: Could not instantiate {type.Name}: {ex.Message}");
        }
    }

    return results;
}

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "UnityPackageScanner.sln")))
            return dir.FullName;
        dir = dir.Parent;
    }

    return Directory.GetCurrentDirectory();
}
